# Generated by Django 4.1 on 2022-08-28 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(default=datetime.datetime.now)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('derece', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
